development:
  adapter: mysql2
  host: localhost  #addr:181.166.1.114
  user: root
  password: 'facuy..'
  database: organizacion_x

test:
  adapter: mysql2
  host: localhost #addr:181.166.1.114
  user: root
  password: 'facuy..'
  database: organizacion_x_test

production:
  adapter: mysql2
  host: localhost #addr:181.166.1.114
  user: root
  password: 'facuy..'
  database: organizacion_x_production
